import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--SOLIDSTEP_MANAGER', type=str, help='Enter SolidStep Manager IP')
parser.add_argument('--METIEYE_MANAGER', type=str, help='Enter MetiEye Manager IP')
args = parser.parse_args()

if args.SOLIDSTEP_MANAGER:
    SOLIDSTEP_CONTROL = 1
else:
    args.SOLIDSTEP_MANAGER = '1.1.1.1'
    SOLIDSTEP_CONTROL = 0

if args.METIEYE_MANAGER:
    METIEYE_CONTROL = 1
else:
    args.METIEYE_MANAGER = '1.1.1.1'
    METIEYE_CONTROL = 0

SACFG = f'''\
[COMMON]
ENCKEY=IE/JSIQa9ZHcL3yiUS2mAw==
ENABLE_ENCRYPT=1
USE_GATEWAY=0
GATEWAY_ADDRESS=
SOLIDSTEP_MANAGER={args.SOLIDSTEP_MANAGER}/SSAI/IG.ssr
METIEYE_MANAGER={args.METIEYE_MANAGER}/MIAI/IG.ssr
CONTROL_CHANGE_ENABLE=0
SOLIDSTEP_CONTROL={SOLIDSTEP_CONTROL}
METIEYE_CONTROL={METIEYE_CONTROL}
MANAGER_USE_HTTPS=1
USE_SSL_CERT=1
SSL_CERT_DIR=
USE_SSL_VERIFY_HOSTNAME=0
CPU_GEAR=8
SA_DIRECTORY=/opt/SSR
CONNECT_TIMEOUT=300
KEEP_LOG_SIZE=1024
KEEP_LOG_DAYS=0
DAILY_GS=2
FORCE_IO_SSL=1

[CLOUD]
ENABLE_CLOUD=1
CLOUD_KEY=

[LOCALDB]
VERY_POOR_RESOURCE=0
CACHE_SIZE=10240

[SA]
HEALTHCHECK=1
INTERVAL=100
SYSINFO_DETECTION=1

[MODULE]
FMR=0

[ENVIRONMENT]
PREPATH=

[AUTOSEARCH]
IPRANGE=<<EOT
EOT\
'''

path = '/SSR/SACFG.ini'
with open(file=path, mode='w+', encoding='utf-8') as f:
    f.write(SACFG)
