FROM ubuntu:22.04

LABEL maintainer="Connor Kwon"
LABEL email1="kwonyounggyu@ssrinc.co.kr"
LABEL email2="connorkyg@gmail.com"
LABEL description="SSR Agent setup"

ARG manager_ip='192.168.199.222'
ARG agent_version='2.41.4841755'
ARG local='/mnt/ssr_mount'

RUN apt update && apt-get install -y \
    python3.9 \
    python3-pip \
    nfs-common
RUN mkdir -p /SSR
COPY $local/$agent_version/linux /SSR

ENTRYPOINT /SSR/SA-linux-64 --start
ENTRYPOINT python3 /tmp/docker/set_perm.py
ENTRYPOINT python3 /tmp/docker/sacfg.py --SOLIDSTEP_MANAGER=$manager_ip

EXPOSE 443/tcp